### ISSUE TITLE
Support babel 7 for .ts / .tsx

### ISSUE THREAD

**Issue by simonbuchan** [gulpjs/interpret#48]
Mentioned this in #47, but got no reply. Babel 7 adds `@babel/preset-typescript`, which, obviously, lets you transpile `.ts/.tsx` code with the babel pipeline (with some limitations). It would be good to be able to use, e.g. `webpackfile.ts` without adding any more dependencies or workarounds.

Looks simple enough to add - just add `@babel/register` with `extensions: '.ts'` to the end of `.ts` - but I'd like feedback on if this is a terrible idea before submitting a PR 🤞

**Comment by phated** [comment]
I'm not a big fan of this idea. But if we do it, I'd want babel to be the last one in the list (excluding deprecated ones)

**Comment by simonbuchan** [comment]
Yeah, you very well could be using both `ts-node` for `.ts` and babel 7 for `.babel.js`. Hah, `.babel.ts`?

**Comment by phated** [comment]
Unfortunately "double" extensions don't work correctly. I think there's an issue about that.
