### ISSUE TITLE
Support es-imports once the API is stable

### ISSUE THREAD

**Issue by phated** [gulpjs/interpret#50]
I don't trust the `.mjs` stuff is going to make it into stable as-is so let's keep an eye on it and support the resulting stable implementation.

**Comment by WuglyakBolgoink** [comment]
any news?

**Comment by phated** [comment]
This is already available in master but it's not going to be published until I can get the test harness updated. https://github.com/gulpjs/interpret/commit/7205800a195d14b2e31de82287858826ef85df10

**Comment by ulrichb** [comment]
Now with Node 13.2 `.mjs` works [without `--experimental-modules`](https://nodejs.org/en/blog/release/v13.2.0/).

=>Can we now delegate `gulpfile.mjs` simply to Node? (Atm. it's not supported.)
