### ISSUE TITLE
Add `plugin-transform-modules-commonjs` to @babel/register

### ISSUE THREAD

**Issue by ulrichb** [gulpjs/interpret#55]
As Node.js nowadays supports every ES 6+ feature necessary for writing idiomatic Gulp4 scripts except ES 6 module imports/exports, it would be cool to automatically add the [`babel-plugin-transform-modules-commonjs`](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs) plugin by using [the `@babel/register` options](https://babeljs.io/docs/en/babel-register). 

This would allow to support Gulp4 style files "out of the box" (okay you still need to install the Babel packages).

But the major benefit would be that you wouldn't need a `.babelrc` file or clutter your `package.json` and thus avoid to potentially interfere with other Babel usages in a project.

**Comment by phated** [comment]
We aren't going to do this. We already support esm, so if you only need modules, just use that instead of bloated babel

**Comment by ulrichb** [comment]
Oh, I din't know of the `.esm.js` option. (And actually had to update `interpret` because of the outdated dependency reference in `gulp`). 

Works great and much faster than Babel. 

Maybe it's worth mentioning this on https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles.

**Comment by phated** [comment]
Glad it's faster for you (it is also to-spec instead of an interop layer)

As for docs, we have an issue open at https://github.com/gulpjs/gulp/issues/2278

**Comment by ulrichb** [comment]
Okay. Thanks!
