### ISSUE TITLE
[ESM] Does not work with "type": "module" in "package.json"

### ISSUE THREAD

**Issue by cedx** [gulpjs/interpret#56]
I'm using the new [ES modules](https://nodejs.org/api/esm.html) features from Node.js 12 (the next LTS).

If I set my package to be an ESM one with the field `type` set to `module` in `package.json` file, the `gulpfile.esm.js` file stops working as expected.

```js
import {spawn} from 'child_process';
       ^
SyntaxError: Unexpected token {
```

If I set the `type` field to `commonjs`, the `gulpfile.esm.js` file works as expected (but not my code which uses only ES modules).
It would be nice if `interpret` could manage this case (i.e. that the new ESM parser is already enabled).

**Comment by phated** [comment]
It's likely not going to happen in interpret because then interpret would need to read package.json files.  Maybe you want to open this on esm?

**Comment by cedx** [comment]
OK, done: standard-things/esm#789
