### ISSUE TITLE
Feature request: add support for the `.cjs` file extension

### ISSUE THREAD

**Issue by cedx** [gulpjs/interpret#59]
Since Node.js 12.x (I don't know the exact version: maybe since 12.11.0), we can use the `.cjs` file extension to denote a JS file using the CommonJS module format.

The issue: if we use `"type": "module"` in `package.json` file, every file which extension ends with `.js` is interpreted as an ES module. With this setting, Gulp fails when loading the `gulpfile.js` file. The only way to force Node.js to interpret the Gulp file as a CommonJS module is to rename it as `gulpfile.cjs`.

If we do this, Gulp doesn't find anymore the `gulpfile.cjs` by itself. We need to use the `--gulpfile` or `-f` command file, which is cumbersome.

**Comment by cedx** [comment]
We can use a `.gulp.json` file at the project root to avoid the need to pass the `-f` option on command line:

```json
{
  "flags": {
    "gulpfile": "gulpfile.cjs"
  }
}
```

I close this ticket because this solution suits me.

**Comment by phated** [comment]
@cedx since node supports `.cjs` natively, I think we can set `.cjs` to `null` in the config but I still need to check.

**Comment by cedx** [comment]
Probably: when I tried, it worked. At least, locally (see #60).
(I closed this issue and the related PR because I had too many issues and PR open, and I wanted to do a cleanup of my GitHub account)
Thanks for your efforts on Gulp!

**Comment by phated** [comment]
It seems that this is only supposed to work when you are executing something with the `node` command directly or importing a `.cjs` file from a `.mjs` file.

I'm not sure why your solution is actually working 😬

**Comment by phated** [comment]
It also seems like `.cjs` doesn't exist in `require.extensions`, which this module is primarily concerned with.

I don't think we can support `.cjs` right now and the workaround will need to suffice. Sorry.
