### ISSUE TITLE
[Request for Comment] Support --transpile-only for gulpfile.ts

### ISSUE THREAD

**Issue by damonmaria** [gulpjs/interpret#70]
## Describe your idea for a new feature

Provide a Gulp option to use the `--transpile-only` mode of ts-node. 

### Explain the problem your idea is trying to solve

Using Typescript as the language of the gulpfile gets very slow once the gulpfile (and it's imports) become a reasonable size. Here's an example I have:
```
[09:03:25] Requiring external module ts-node/register
[09:03:32] Using gulpfile ~/development/mindhive/tannery/deploy/gulpfile.ts
```

It takes 7 seconds to transpile the gulpfile on a top-end MacBook Pro. This could be substantially faster if Gulp used `--transpile-only`.

### How will it benefit gulp and its users?

Gulp could be much faster for Typescript users.

### If this feature could exist outside of gulp (like as a plugin or a module), would you be interested in helping to create and maintain it?

I don't think this is possible to be outside of Gulp itself.

**Comment by damonmaria** [comment]
Ah, I did not realize you could use sucrase. I searched the gulpjs.com documentation but it only seems to mention ts-node. 

I'd love to try sucrase but my build also uses `serverless-webapck` which has ts-node as an (optional) dependency. And so Gulp chooses ts-node over sucrase. So maybe this feature request should change to the ability to specify to gulp (even through an environment var) a preferred transpiler. As currently the only control of this (when multiple transpilers are valid for the file extension) is what transpilers are installed, which we don't always have control over.

**Comment by phated** [comment]
Instead of committing to using `transpile only` with ts-node, I've added extra extensions to force additional loaders, such as `.sucrase.ts`, on the master branch. These will be released with v3
