### ISSUE TITLE
Support tsconfig "paths" runtime module resolution

### ISSUE THREAD

**Issue by gamedevsam** [gulpjs/interpret#72]
### Describe your idea for a new feature

In order to support TypeScript's "paths" config option, this project should load `tsconfig-paths/register` when loading ts files: https://www.npmjs.com/package/tsconfig-paths

### Explain the problem your idea is trying to solve

Currently projects that leverage the [paths typescript configuration](https://www.typescriptlang.org/tsconfig#paths) cannot use interpret successfully.

### How will it benefit gulp and its users?

It will improve TypeScript compatibility by supporting the "paths" config option. 

### If this feature could exist outside of gulp (like as a plugin or a module), would you be interested in helping to create and maintain it?

No time... sorry.

**Comment by phated** [comment]
Why isn't that just upstreamed into ts-node if it is an official feature of typescript? I'd prefer this to be in the tool where it belongs.
