### ISSUE TITLE
Add support for SWC transforms

### ISSUE THREAD

**Issue by danilofuchs** [gulpjs/interpret#76]
### Describe your idea for a new feature

Add `@swc/register` or `@swc-node/register` (I'm not sure which is more stable) to the interpreter list

### Explain the problem your idea is trying to solve

We are migrating away from ts-node to swc for faster compilations

### How will it benefit gulp and its users?

- Faster build times
- Usage is not mandatory

### If this feature could exist outside of gulp (like as a plugin or a module), would you be interested in helping to create and maintain it?

No

**Comment by phated** [comment]
Why open this when it's being worked on in #74 ?

**Comment by phated** [comment]
Closed by #74 but I'm also planning to add `.swc.(js|jsx|ts|tsx)` extensions to match babel and esbuild.
