### ISSUE TITLE
`tsimp` support

### ISSUE THREAD

**Issue by wojtekmaj** [gulpjs/interpret#97]
### Describe your idea for a new feature

tsimp is a ts-node alternative that quickly gains popularity due to its speed.

### Explain the problem your idea is trying to solve

I'd like https://github.com/webpack/webpack-cli/issues/4025 to be fixed.

### How will it benefit gulp and its users?

They will be able to use yet another module loader.

### If this feature could exist outside of gulp (like as a plugin or a module), would you be interested in helping to create and maintain it?

It cannot exist outside of this package.

**Comment by phated** [comment]
170 weekly downloads is not enough. Additionally, interpret doesn't support the node loader feature yet.
